table:
  name: user_profiles
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: userProfiles
  custom_root_fields:
    delete: deleteUserProfiles
    delete_by_pk: deleteUserProfile
    insert: insertUserProfiles
    insert_one: insertUserProfile
    select: userProfiles
    select_by_pk: userProfile
    update: updateUserProfiles
    update_by_pk: updateUserProfile
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - is_subscribed_general
        - is_subscribed_sync_updates
        - sync_updates_frequency
        - timezone
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - is_subscribed_general
        - is_subscribed_sync_updates
        - sync_updates_frequency
        - timezone
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
event_triggers:
  - name: handelDeleteUserProfile
    definition:
      delete:
        columns: '*'
      enable_manual: false
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: handleUpsertUserProfle
    definition:
      enable_manual: true
      insert:
        columns: '*'
      update:
        columns:
          - is_subscribed_sync_updates
          - timezone
          - sync_updates_frequency
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
