table:
  name: destinations
  schema: public
object_relationships:
  - name: airtable_config
    using:
      manual_configuration:
        column_mapping:
          id: destination_id
        insertion_order: after_parent
        remote_table:
          name: airtable_configs
          schema: public
  - name: coda_config
    using:
      manual_configuration:
        column_mapping:
          id: destination_id
        insertion_order: after_parent
        remote_table:
          name: coda_configs
          schema: public
  - name: integration
    using:
      foreign_key_constraint_on: integration_id
  - name: notion_connection
    using:
      manual_configuration:
        column_mapping:
          notion_connection_id: bot_id
          user_id: user_id
        insertion_order: null
        remote_table:
          name: notion_connections
          schema: public
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: account_connections
    using:
      foreign_key_constraint_on:
        column: destination_id
        table:
          name: destination_accounts
          schema: public
  - name: destination_sync_logs
    using:
      foreign_key_constraint_on:
        column: destination_id
        table:
          name: destination_sync_logs
          schema: public
insert_permissions:
  - role: user
    permission:
      check: {}
      set:
        user_id: x-hasura-User-Id
      columns:
        - authentication
        - integration_id
        - is_ready
        - name
        - notion_connection_id
        - should_sync_investments
        - should_sync_transactions
        - sync_start_date
        - table_configs
select_permissions:
  - role: user
    permission:
      columns:
        - authentication
        - created_at
        - disabled_at
        - id
        - integration_id
        - is_ready
        - name
        - notion_connection_id
        - should_override_transaction_name
        - should_sync_investments
        - should_sync_transactions
        - sync_start_date
        - table_configs
        - updated_at
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - authentication
        - disabled_at
        - name
        - notion_connection_id
        - should_override_transaction_name
        - should_sync_investments
        - should_sync_transactions
        - sync_start_date
        - table_configs
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check:
        user_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: onInsertDestination
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: onUpdateDestination
    definition:
      enable_manual: false
      update:
        columns:
          - disabled_at
          - table_configs
          - name
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
