table:
  name: notion_connections
  schema: public
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: destinations
    using:
      manual_configuration:
        column_mapping:
          bot_id: notion_connection_id
          user_id: user_id
        insertion_order: null
        remote_table:
          name: destinations
          schema: public
select_permissions:
  - role: user
    permission:
      columns:
        - bot_id
        - access_token
        - workspace_id
        - workspace_name
        - workspace_icon
        - owner
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: onInsertNotionConnection
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
