table:
  name: coda_configs
  schema: public
object_relationships:
  - name: destination
    using:
      foreign_key_constraint_on: destination_id
insert_permissions:
  - role: user
    permission:
      check:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
      columns:
        - access_token_hash
        - created_at
        - destination_id
        - id
        - is_ready
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - destination_id
        - id
        - is_ready
      filter:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
